{{- if .Values.namespace.create }}
# Logsenta - Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "logsenta.namespace" . }}
  labels:
    {{- include "logsenta.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
{{- end }}
